export const FUMBLES: {  minRange: number, maxRange: number, text: string }[] = [
    { minRange: 1,  maxRange: 5, text: 'Pierdes la siguiente parada.' },
    { minRange: 6,  maxRange: 10, text: 'Pierdes el siguiente ataque.' },
    { minRange: 11,  maxRange: 15, text: 'Pierdes el siguiente ataque y la siguiente parada.' },
    { minRange: 16,  maxRange: 20, text: 'Pierdes el siguiente ataque y la siguiente parada, así como la esquiva.' },
    { minRange: 21,  maxRange: 25, text: 'Pierdes los siguientes 1D3 ataques.' },
    { minRange: 26,  maxRange: 30, text: 'Pierdes los siguientes 1D3 ataques y paradas.' },
    { minRange: 31,  maxRange: 35, text: 'Se rompe la sujeción del escudo y lo pierdes de inmediato' },
    { minRange: 36,  maxRange: 40, text: 'Se rompe la sujeción del escudo y lo pierdes de inmediato junto con el siguiente ataque.' },
    { minRange: 41,  maxRange: 45, text: 'Se rompe una correa de la armadura y se le suelta una pieza (tira la localización de golpe para determinar qué pieza de la armadura se desprende).' },
    { minRange: 46,  maxRange: 50, text: 'Se rompe una correa de la armadura y se le suelta una pieza (como arriba). También pierde el siguiente ataque y la siguiente parada.' },
    { minRange: 51,  maxRange: 55, text: 'Se cae y pierde la parada en el asalto actual. Tarda 1D3 asaltos en levantarse.' },
    { minRange: 56,  maxRange: 60, text: 'Se tuerce un tobillo; su Movimiento se reduce a la mitad durante 5D10 asaltos.' },
    { minRange: 61,  maxRange: 63, text: 'Se tuerce un tobillo, su Movimiento se reduce a la mitad durante 5D10 asaltos, cae al suelo y pierde la parada en el asalto actual. Tarda 1D3 asaltos en levantarse.' },
    { minRange: 64,  maxRange: 67, text: 'Visión afectada; pierde un 25% en ataques y paradas. Necesita pasar 1D3 asaltos sin estar trabado en combate para aclararse la visión.' },
    { minRange: 68,  maxRange: 70, text: 'Visión afectada; pierde un 50% en ataques y paradas. Necesita pasar 1D6 asaltos sin estar trabado en combate para aclararse la visión.' },
    { minRange: 71,  maxRange: 72, text: 'Visión impedida; pierde todos los ataques y paradas. Necesita pasar 1D6 asaltos sin estar trabado en combate para aclararse la visión.' },
    { minRange: 73,  maxRange: 74, text: 'Distracción; los enemigos le atacarán con un +25% durante el siguiente asalto.' },
    { minRange: 75,  maxRange: 78, text: 'Ataque: Deja caer el arma empleada en el ataque (tarda 1D3 asaltos en recuperarla).\nParada: Deja caer el arma o escudo empleado en la parada (tarda 1D3 asaltos en recuperarlo).' },
    { minRange: 79,  maxRange: 82, text: 'Ataque: El arma sale despedida a 1D6 metros de distancia. Tira 1D8 para determinar la dirección:\n1=norte, 2=noreste, 3=este, 4=sureste, 5=sur, 6=suroeste, 7=oeste, 8=noroeste.\nParada: El arma o escudo empleado en la parada sale despedido a 1D6 metros de distancia. Tira 1D8 para determinar la dirección (ver arriba).' },
    { minRange: 83,  maxRange: 86, text: 'Ataque: El arma se rompe (la probabilidad es del 100% si no está encantada, pero se puede reducir en un 10% por cada punto de magia de batalla que se hubiera lanzado sobre ella, y en un 20% por cada punto de magia rúnica).\nParada: El arma o escudo empleado en la parada se rompe (la probabilidad es del 100% si no está encantada, pero se puede reducir en un 10% por cada punto de magia de batalla que se hubiera lanzado sobre ella, y en un 20% por cada punto de magia rúnica).' },
    { minRange: 87,  maxRange: 89, text: 'Ataque: El ataque golpea al amigo más cercano, infligiéndole el daño normal (si no hay cerca ningún amigo, se golpea a sí mismo).\nParada: La guardia queda abierta y el adversario golpea automáticamente infligiendo el daño normal.' },
    { minRange: 90,  maxRange: 91, text: 'Ataque: El ataque golpea al amigo más cercano, infligiéndole el máximo daño (si no hay cerca ningún amigo, se golpea a sí mismo).\nParada: La guardia queda abierta y el adversario golpea automáticamente infligiendo el daño normal.' },
    { minRange: 92,  maxRange: 92, text: 'Ataque: El ataque golpea al amigo más cercano con un resultado de éxito crítico (si no hay cerca ningún amigo, se golpea a sí mismo).\nParada: La guardia queda abierta y el adversario golpea automáticamente infligiendo el daño normal.' },
    { minRange: 93,  maxRange: 95, text: 'Ataque: Se golpea a sí mismo infligiéndose el daño normal.\nParada: La guardia queda abierta y el adversario golpea automáticamente infligiendo el máximo daño.' },
    { minRange: 96,  maxRange: 97, text: 'Ataque: Se golpea a sí mismo infligiéndose el daño máximo.\nParada: La guardia queda abierta y el adversario golpea automáticamente con un resultado de éxito crítico.' },
    { minRange: 98,  maxRange: 98, text: 'Ataque: Se golpea a sí mismo con un resultado de éxito crítico.\nParada: La guardia queda abierta y el adversario golpea automáticamente con un resultado de éxito crítico.' },
    { minRange: 99,  maxRange: 99, text: '¡La ha hecho buena! Tira dos veces en esta misma tabla y aplica ambos resultados. Si vuelve a salir este resultado, tira de nuevo hasta conseguir dos resultados diferentes.' },
    { minRange: 100,  maxRange: 100, text: '¡La ha hecho buena del todo! Tira tres veces en esta misma tabla y aplica los tres resultados obtenidos. Si vuelve a salir este resultado, tira de nuevo hasta conseguir tres resultados diferentes' }
];