export const MELEE_FUMBLES: { minRange: number, maxRange: number, text: string }[] = [
    { minRange: 1, maxRange: 5, text: 'Pierdes la siguiente detención.' },
    { minRange: 6, maxRange: 10, text: 'Pierdes el siguiente ataque.' },
    { minRange: 11,  maxRange: 15, text: 'Pierdes la siguiente detención y el siguiente ataque.' },
    { minRange: 16,  maxRange: 20, text: 'Pierdes la siguiente detención y el siguiente ataque y la siguiente esquiva.' },
    { minRange: 21,  maxRange: 25, text: 'Pierdes la los siguientes 1D3 ataques.' },
    { minRange: 26,  maxRange: 30, text: 'Pierdes los siguientes 1D3 ataques y las siguientes 1D3 detenciones.' },
    { minRange: 31,  maxRange: 35, text: 'La sujeción del escudo se rompe y este cae al suelo.' },
    { minRange: 36,  maxRange: 40, text: 'La sujeción del escudo se rompe, este cae al suelo y pierdes el siguiente ataque.' },
    { minRange: 41,  maxRange: 45, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida.' },
    { minRange: 46,  maxRange: 50, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida y pierdes el siguiente ataque y la siguiente detención.' },
    { minRange: 51,  maxRange: 55, text: 'Cae al suelo, pierde todas las detenciones y esquivas de este asalto y tarda 1D3 asaltos en volver a levantarse.' },
    { minRange: 56,  maxRange: 60, text: 'Torcedura de tobillo, la tasa de movimiento se ve reducida a la mitad durante 5D10 asaltos.' },
    { minRange: 61,  maxRange: 63, text: 'Torcedura de tobillo y caida, la tasa de movimiento se ve reducida a la mitad durante 5D10 asaltos y pierdes el siguiente ataque, además cae al suelo, pierde todas las detenciones y esquivas de este asalto y tarda 1D3 asaltos en volver a levantarse' },
    { minRange: 64,  maxRange: 67, text: 'Visión empañada, se pierden 25 percentiles en todos los ataques y detenciones ,para volver aajustarse el casco o aclararse la vista son necesarios 1D3 asaltos exclusivamente haciendo eso.' },
    { minRange: 68,  maxRange: 70, text: 'Visión empañada, se pierden 50 percentiles en todos los ataques y detenciones ,para volver aajustarse el casco o aclararse la vista son necesarios 1D6 asaltos exclusivamente haciendo eso.' },
    { minRange: 71,  maxRange: 72, text: 'Visión Impedida: se pierden TODOS los ataques y las detenciones, para volver a ajustarse el casco o aclararse la vista son necesarios 1D6 asaltos exclusivamente haciendo eso.' },
    { minRange: 73,  maxRange: 74, text: 'Distracción: Durante el siguiente asalto los enemigos te golpean con un bono de +25% en sus ataques.' },
    { minRange: 75,  maxRange: 78, text: 'El arma cae y se tarda 1D2 asaltos en recuperar.' },
    { minRange: 79,  maxRange: 82, text: 'El arma sale despedida a 1D6 m. de distancia se ha de lanzar 1D8 para determinar cual, se tarda 1D3+1 asaltos en recuperarla' },
    { minRange: 83,  maxRange: 86, text: 'El arma se rompe, si está encantada se reduce el porcentaje desde el 100% en 10% por cada punto de magia espiritual o hechicería y en 20% por cada punto divino' },
    { minRange: 87,  maxRange: 89, text: 'ATAQUE: Golpea al amigo más cercano, haciendo daño normal, si no hay amigo cercano se golpea a si mismo\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe automático con daño normal.' },
    { minRange: 90,  maxRange: 91, text: 'ATAQUE: Golpea al amigo más cercano, haciendo daño máximo del arma, si no hay amigo cercano se golpea a si mismo\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe automático con daño normal.' },
    { minRange: 92,  maxRange: 92, text: 'ATAQUE: Golpea al amigo más cercano, haciendo daño máximo del arma e ignorando armadura, si no hay amigo cercano se golpea a si mismo\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe automático con daño normal.' },
    { minRange: 93,  maxRange: 95, text: 'ATAQUE: Se golpea a si mismo haciendo daño normal del arma\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe automático con daño normal.' },
    { minRange: 96,  maxRange: 97, text: 'ATAQUE: Se golpea a si mismo haciendo daño máximo del arma\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe automático con daño normal.' },
    { minRange: 98,  maxRange: 98, text: 'ATAQUE: Se golpea a si mismo haciendo daño máximo del arma e ignorando cualquier armadura\nDEFENSA: La guardia queda abierta, el adversario consigue un golpe crítico automático.' },
    { minRange: 99,  maxRange: 99, text: 'La has hecho buena, Tira dos veces en esta tabla y aplica ambos resultados.' },
    { minRange: 100,  maxRange: 100, text: 'La has hecho buena del todo, Tira tres veces en esta tabla y aplica todos los resultados obtenidos.' },
];

export const RANGED_FUMBLES: {  minRange: number, maxRange: number, text: string }[] = [
    { minRange: 1,  maxRange: 10, text: 'Pierdes el siguiente ataque.' },
    { minRange: 11,  maxRange: 20, text: 'Pierdes los siguientes 1D4 ataques.' },
    { minRange: 21,  maxRange: 30, text: 'En los siguientes 1D3 asaltos no podrá realizar actividad ninguna.' },
    { minRange: 31,  maxRange: 40, text: 'La sujeción del arma se rompe y esta cae al suelo.' },
    { minRange: 41,  maxRange: 50, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida.' },
    { minRange: 51,  maxRange: 60, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida y no puedes llevar a acbo actividad alguna durante el siguiente asalto.' },
    { minRange: 61,  maxRange: 65, text: 'Caes al suelo.' },
    { minRange: 66,  maxRange: 70, text: 'Visión empañada, pierdes 50% en todos los ataques durante 1D3 asaltos.' },
    { minRange: 71,  maxRange: 73, text: 'Visión impedida ,no puedes hacer nada durante 1D6 asaltos.' },
    { minRange: 74,  maxRange: 80, text: 'El arma sale despedida a 1D6 m. de distancia se ha de lanzar 1D8 para determinar cual, se tarda 1D3+1 asaltos en recuperarla.' },
    { minRange: 81,  maxRange: 85, text: 'El arma se rompe, si está encantada se reduce el porcentaje desde el 100% en 10% por cada punto de magia espiritual o hechicería y en 20% por cada punto divino.' },
    { minRange: 86,  maxRange: 89, text: 'Golpea al amigo más cercano, haciendo daño normal, si no hay amigo cercano el arma se rompe, si está encantada se reduce el porcentaje desde el 100% en 10% por cada punto de magia espiritual o hechicería y en 20% por cada punto divino.' },
    { minRange: 90,  maxRange: 92, text: 'Golpea al amigo más cercano, haciendo daño de empalamiento, si es posible, si no hay amigo cercano el arma se rompe, si está encantada se reduce el porcentaje desde el 100% en 10% por cada punto de magia espiritual o hechicería y en 20% por cada punto divino.' },
    { minRange: 93,  maxRange: 94, text: 'Golpea al amigo más cercano, haciendo daño crítico, si no hay amigo cercano el arma se rompe, si está encantada se reduce el porcentaje desde el 100% en 10% por cada punto de magia espiritual o hechicería y en 20% por cada punto divino.' },
    { minRange: 95,  maxRange: 98, text: 'La has hecho buena, Tira dos veces en esta tabla y aplica ambos resultados.' },
    { minRange: 99,  maxRange: 100, text: 'La has hecho buena del todo, Tira tres veces en esta tabla y aplica todos los resultados obtenidos.' }
];

export const NATURAL_FUMBLES: {  minRange: number, maxRange: number, text: string }[] = [
    { minRange: 1,  maxRange: 5, text: 'Pierdes la siguiente esquiva.' },
    { minRange: 6,  maxRange: 10, text: 'Pierdes el siguiente ataque.' },
    { minRange: 11,  maxRange: 15, text: 'Pierdes la siguiente esquiva y la siguiente detención.' },
    { minRange: 16,  maxRange: 20, text: 'Pierdes la siguiente esquiva y la siguiente detención y el siguiente ataque.' },
    { minRange: 21,  maxRange: 25, text: 'Durante 1D3 asaltos no puedes iniciar acción alguna ni detener.' },
    { minRange: 26,  maxRange: 30, text: 'Pierdes los siguientes 1D6 ataques' },
    { minRange: 31,  maxRange: 35, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida' },
    { minRange: 36,  maxRange: 40, text: 'La sujeción de una pieza de armadura al azar se rompe y esta queda desprotegida y pierdes el siguiente asalto, no puedes iniciar acción alguna ni detener.' },
    { minRange: 41,  maxRange: 50, text: 'Cae al suelo, pierde todas las detenciones y esquivas de este asalto y tarda 1D3 asaltos en volver a levantarse' },
    { minRange: 51,  maxRange: 60, text: 'Cae al suelo y torcedura de tobillo, la tasa de movimiento se ve reducida a la mitad durante 5D10 asaltos' },
    { minRange: 61,  maxRange: 70, text: 'Visión empañada, se pierden 25 percentiles en todos los ataques y detenciones ,para volver aajustarse el casco o aclararse la vista son necesarios 1D3 asaltos exclusivamente haciendo eso' },
    { minRange: 71,  maxRange: 75, text: 'Visión impedida ,no puedes hacer nada durante 1D3 asaltos' },
    { minRange: 76,  maxRange: 80, text: 'Distracción: Durante el siguiente asalto los enemigos te golpean con un bono de +25% en sus ataques' },
    { minRange: 81,  maxRange: 85, text: 'Distensión muscular en la localización usada para atacar, pierde 1 PV y 3 PF' },
    { minRange: 86,  maxRange: 90, text: 'Golpea al amigo más cercano, haciendo daño normal, si no hay amigo cercano: Distensión muscular en la localización usada para atacar, pierde 1 PV y 3 PF' },
    { minRange: 91,  maxRange: 94, text: 'Golpea al amigo más cercano, haciendo daño máximo del arma, si no hay amigo cercano: Distensión muscular en la localización usada para atacar, pierde 1 PV y 3 PF' },
    { minRange: 95,  maxRange: 98, text: 'Se golpea a si mismo haciendose máximo daño' },
    { minRange: 99,  maxRange: 99, text: 'La has hecho buena, Tira dos veces en esta tabla y aplica ambos resultados.' },
    { minRange: 100,  maxRange: 100, text: 'La has hecho buena del todo, Tira tres veces en esta tabla y aplica todos los resultados obtenidos.' },
];